/**
 * Generate a FastHenry input file (.inp) from a ConductorNetwork.
 *
 * This allows validation of our PEEC solver against FastHenry.
 * The generated file can be run with FastHenry to compare impedance results.
 */

import type { ConductorNetwork, ConductorNode } from '$lib/geometry/network';
import type { ProcessStack } from '$lib/stack/types';
import { getStackLayer } from '$lib/stack/types';

export interface FastHenryExportOptions {
	title?: string;
	fMin: number;  // Hz
	fMax: number;  // Hz
	nDec?: number; // points per decade (default 5)
}

/**
 * Generate FastHenry .inp file content from a conductor network.
 */
export function generateFastHenryInput(
	network: ConductorNetwork,
	stack: ProcessStack,
	options: FastHenryExportOptions,
): string {
	const { title = 'RapidPassives Export', fMin, fMax, nDec = 5 } = options;

	const nodeMap = new Map<string, ConductorNode>();
	for (const n of network.nodes) nodeMap.set(n.id, n);

	const lines: string[] = [];

	// Title
	lines.push(`* ${title}`);
	lines.push('* Generated by RapidPassives PEEC solver');
	lines.push('');

	// Units in micrometers
	lines.push('.Units um');
	lines.push('');

	// Default conductivity (copper)
	lines.push('.Default sigma=5.8e7');
	lines.push('');

	// Nodes — FastHenry uses "Nname x=... y=... z=..."
	const nodeNames = new Map<string, string>();
	let nodeIdx = 0;
	for (const node of network.nodes) {
		const sl = getStackLayer(stack, node.layerId);
		const z = sl ? sl.z + sl.thickness / 2 : 300;
		const name = `N${nodeIdx++}`;
		nodeNames.set(node.id, name);
		lines.push(`${name} x=${node.x.toFixed(3)} y=${node.y.toFixed(3)} z=${z.toFixed(3)}`);
	}
	lines.push('');

	// Segments — FastHenry uses "Ename Nfrom Nto w=... h=... sigma=..."
	let segIdx = 0;
	for (const seg of network.segments) {
		const from = nodeMap.get(seg.fromNode);
		const to = nodeMap.get(seg.toNode);
		if (!from || !to) continue;

		const fromName = nodeNames.get(seg.fromNode);
		const toName = nodeNames.get(seg.toNode);
		if (!fromName || !toName) continue;

		// Check segment has non-zero length
		const dx = to.x - from.x;
		const dy = to.y - from.y;
		if (Math.sqrt(dx * dx + dy * dy) < 1e-6) continue;

		const sl = getStackLayer(stack, seg.layerId);
		const h = sl?.thickness ?? 1;
		const sigma = sl?.rsh ? 1 / (sl.rsh * h * 1e-6) : 5.8e7;

		const name = `E${segIdx++}`;
		lines.push(`${name} ${fromName} ${toName} w=${seg.width.toFixed(3)} h=${h.toFixed(3)} sigma=${sigma.toExponential(2)}`);
	}
	lines.push('');

	// Via segments — model each via array as equivalent vertical segments
	for (const via of network.vias) {
		const topName = nodeNames.get(via.topNode);
		const botName = nodeNames.get(via.bottomNode);
		if (!topName || !botName) continue;

		// Model via array as .equiv (ideal short) for simplicity
		// FastHenry doesn't handle via arrays natively — an .equiv
		// node equivalence is the closest approximation
		lines.push(`* Via: ${via.id} (${via.polygons.length} via polygons)`);
		lines.push(`.equiv ${topName} ${botName}`);
	}
	lines.push('');

	// External ports
	for (const port of network.ports) {
		const plusName = nodeNames.get(port.plusNode);
		const minusName = nodeNames.get(port.minusNode);
		if (plusName && minusName) {
			lines.push(`.external ${plusName} ${minusName}`);
		}
	}
	lines.push('');

	// Frequency sweep
	if (fMin > 0) {
		lines.push(`.freq fmin=${fMin.toExponential(2)} fmax=${fMax.toExponential(2)} ndec=${nDec}`);
	} else {
		lines.push(`.freq fmin=0 fmax=${fMax.toExponential(2)} ndec=${nDec}`);
	}
	lines.push('');
	lines.push('.end');

	return lines.join('\n');
}

/** Trigger download of FastHenry input file */
export function downloadFastHenryInput(content: string, filename: string = 'inductor.inp'): void {
	const blob = new Blob([content], { type: 'text/plain' });
	const url = URL.createObjectURL(blob);
	const a = document.createElement('a');
	a.href = url;
	a.download = filename;
	a.click();
	URL.revokeObjectURL(url);
}
